[build]
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"

# Security redirects
[[redirects]]
  from = "/admin/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/.env"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/wp-admin/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/phpmyadmin/*"
  to = "/404.html"
  status = 404

# Main app redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Security headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    # Prevent clickjacking
    X-Frame-Options = "DENY"
    
    # XSS Protection
    X-XSS-Protection = "1; mode=block"
    
    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
    
    # Referrer policy
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Remove server info
    X-Powered-By = ""
    Server = ""
    
    # Content Security Policy - Enhanced
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://fonts.googleapis.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com https://cdn.jsdelivr.net; img-src 'self' data: https: blob:; connect-src 'self' https://trading-screener-lerd2.ondigitalocean.app https://*.digitalocean.com https://api.alpaca.markets wss://*.digitalocean.com; media-src 'self'; object-src 'none'; child-src 'none'; worker-src 'self' blob:; manifest-src 'self'; base-uri 'self'; form-action 'self';"
    
    # Permissions Policy (formerly Feature Policy)
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    
    # HTTP Strict Transport Security
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # DNS Prefetch Control
    X-DNS-Prefetch-Control = "off"
    
    # Rate limiting hint
    X-RateLimit-Limit = "1000"
    X-RateLimit-Window = "3600"

# API endpoints with stricter CSP
[[headers]]
  for = "/api/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; connect-src 'self' https://trading-screener-lerd2.ondigitalocean.app;"
    Access-Control-Allow-Origin = "https://hutztrades.com"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Max-Age = "86400"

# Static assets with long cache and security
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# HTML with shorter cache and security headers
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"
    X-Content-Type-Options = "nosniff"

# Block common attack vectors
[[headers]]
  for = "/*.php"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/*.asp"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"